// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NonProfitSiteV3.Data;

#nullable disable

namespace NonProfitSiteV3.Migrations.AppDbContext03Migrations
{
    [DbContext(typeof(AppDbContext03))]
    partial class AppDbContext03ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NonProfitSiteV3.Models.Doctors", b =>
                {
                    b.Property<int>("Doc_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Doc_Id"), 1L, 1);

                    b.Property<string>("Doc_city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doc_contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doc_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doc_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doc_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Doc_Id");

                    b.ToTable("DoctorsList2");
                });

            modelBuilder.Entity("NonProfitSiteV3.Models.TreatmentCenters", b =>
                {
                    b.Property<int>("TC_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TC_Id"), 1L, 1);

                    b.Property<string>("TC_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC_contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TC_Id");

                    b.ToTable("TreatmentCentersList2");
                });
#pragma warning restore 612, 618
        }
    }
}
