// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NonProfitSiteV3.Data;

#nullable disable

namespace NonProfitSiteV3.Migrations.AppDbContext04Migrations
{
    [DbContext(typeof(AppDbContext04))]
    [Migration("20220714112709_AddDonationTable")]
    partial class AddDonationTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NonProfitSiteV3.Models.Donation", b =>
                {
                    b.Property<int>("Don_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Don_ID"), 1L, 1);

                    b.Property<int>("Don_amount")
                        .HasColumnType("int");

                    b.Property<string>("Don_contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Don_details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Don_email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Don_ID");

                    b.ToTable("DonationTable");
                });
#pragma warning restore 612, 618
        }
    }
}
