// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NonProfitSiteV3.Data;

#nullable disable

namespace NonProfitSiteV3.Migrations.AppDbContext05Migrations
{
    [DbContext(typeof(AppDbContext05))]
    partial class AppDbContext05ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NonProfitSiteV3.Models.VolunteerApplicants", b =>
                {
                    b.Property<int>("VA_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VA_Id"), 1L, 1);

                    b.Property<string>("VA_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VA_contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VA_dob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VA_education")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VA_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VA_experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VA_father")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VA_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VA_religion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VA_Id");

                    b.ToTable("VolAppTable");
                });
#pragma warning restore 612, 618
        }
    }
}
