// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NonProfitSiteV3.Data;

#nullable disable

namespace NonProfitSiteV3.Migrations.AppDbContext07Migrations
{
    [DbContext(typeof(AppDbContext07))]
    partial class AppDbContext07ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NonProfitSiteV3.Models.Events", b =>
                {
                    b.Property<int>("Ev_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ev_Id"), 1L, 1);

                    b.Property<string>("Ev_location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ev_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ev_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ev_timedate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ev_Id");

                    b.ToTable("EventsTable");
                });
#pragma warning restore 612, 618
        }
    }
}
