// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NonProfitSiteV3.Data;

#nullable disable

namespace NonProfitSiteV3.Migrations.AppDbContext06Migrations
{
    [DbContext(typeof(AppDbContext06))]
    [Migration("20220717064243_AddRegVolTable")]
    partial class AddRegVolTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NonProfitSiteV3.Models.VolunteerRegistered", b =>
                {
                    b.Property<int>("VReg_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VReg_Id"), 1L, 1);

                    b.Property<string>("VReg_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VReg_branch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VReg_contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VReg_dob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VReg_education")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VReg_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VReg_experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VReg_father")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VReg_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VReg_religion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VReg_Id");

                    b.ToTable("RegisteredVolunteerTable");
                });
#pragma warning restore 612, 618
        }
    }
}
